name: Maven Dependency Downloader

on:
  workflow_dispatch:
    inputs:
      maven_url:
        description: 'Maven URL for dependencies'
        required: true
        type: string

jobs:
  download_dependencies:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v5.3.0

    - name: Set up Java
      uses: actions/setup-java@v4.6.0
      with:
        distribution: 'oracle'
        java-version: '21'

    - name: Install Maven
      run: sudo apt-get install -y maven

    - name: Run Maven downloader script
      run: |
        python ./maven_downloader.py "${{ github.event.inputs.maven_url }}"

    - name: Upload dependencies as artifact
      uses: actions/upload-artifact@v4
      with:
        name: maven-dependencies
        path: ./local-repo/dependencies
